### PR TITLE
Added new icon for main navigation

### PR DESCRIPTION
**Pull request by gergo85**

### CODE REVIEW

**Comment by MatissJanis** [comment]
Could you explain: why do we need a new icon? Seems like such a minuscule thing.

**Comment by gergo85** [comment]
I think it is nicer than the default icon. Furthermore it is same than the plugin icon on the market. The all official plugins use svg icon.

**Comment by MatissJanis** [comment]
That's subjective.

It's better to keep the current icon because:
1. we don't want to confuse the current users of this plugin;
2. we don't want to add extra load - keeping a font-icon is slightly faster.

**Comment by gergo85** [comment]
I understand.

**Pull request closed without merging**
